Traceback (most recent call last):
  File "test/test_model.py", line 58, in <module>
    config = json.load(f)
  File "/Users/phamvanmanh/opt/anaconda3/envs/tensor_env/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/phamvanmanh/opt/anaconda3/envs/tensor_env/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/phamvanmanh/opt/anaconda3/envs/tensor_env/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/phamvanmanh/opt/anaconda3/envs/tensor_env/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)